// src/ui/components/Social.tsx
import React from 'react'
import {
  FaGithub,
  FaLinkedin,
  FaIdBadge,
  FaTwitter,
  FaDev
} from 'react-icons/fa'
import { IconType } from 'react-icons/lib/cjs'
import './Social.css'

const IconLink: React.FC<{
  link: string
  title: string
  Icon: IconType
}> = props => {
  const { link, title, Icon } = props
  // if the link starts with 'http://' or 'https://', its not local.
  const isNotLocal = /^https?:\/\//.test(link)

  return (
    <a
      {...{
        rel: isNotLocal ? 'noopener noreferrer' : undefined,
        target: '_blank',
        href: link,
        title
      }}
    >
      <Icon />
    </a>
  )
}

export const Github = () => (
  <IconLink
    title="Check out my Github"
    link="https://github.com/chrismilson"
    Icon={FaGithub}
  />
)

export const Linkedin = () => (
  <IconLink
    title="Have a look at my Linkedin"
    link="https://linkedin.com/in/chris-milson"
    Icon={FaLinkedin}
  />
)

export const Resume = () => (
  <IconLink
    title="Take a peek at my resume..."
    link="CV.pdf"
    Icon={FaIdBadge}
  />
)

export const Twitter = () => (
  <IconLink
    title="...Tweet tweet"
    link="https://twitter.com/_shlappas"
    Icon={FaTwitter}
  />
)

export const Dev = () => (
  <IconLink
    title="I have no posts here!!"
    link="https://dev.to/chrismilson"
    Icon={FaDev}
  />
)

const Social: React.FC = () => (
  <div className="Social">
    <Github />
    <Linkedin />
    <Resume />
  </div>
)

export default Social

// src/app/social/social.component.ts
import { Component, OnInit } from '@angular/core';
import {
  faGithub,
  faLinkedin
} from '@fortawesome/free-brands-svg-icons';
import {
  faIdBadge
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-social',
  templateUrl: './social.component.html',
  styles: [`
    .icon-list {
      font-size: 1.5rem;
      position: fixed;
      top: 0;
      right: 0;

      display: flex;
    }

    a {
      color: inherit;
      margin: 0.5rem;
    }
  `]
})
export class SocialComponent {
  icons = [
    {
      name: 'Github',
      title: 'Check out my Github',
      icon: faGithub,
      link: 'https://github.com/chrismilson'
    },
    {
      name: 'Linkedin',
      title: '...or my Linkedin',
      icon: faLinkedin,
      link: 'https://www.linkedin.com/in/chris-milson/'
    },
    {
      name: 'CV',
      title: 'Have a look at my CV too',
      icon: faIdBadge,
      link: 'assets/CV.pdf'
    }
  ];
}

<div class="icon-list">
  <a
    *ngFor="let icon of icons"
    [title]="icon.title"
    [href]="icon.link"
  >
    <fa-icon [icon]="icon.icon"></fa-icon>
  </a>
</div>
